### ISSUE TITLE
BrokenPipeError: [Errno 32] Broken pipe

### ISSUE THREAD

**Issue by afmsaif** [pyaf/DenseNet-MURA-PyTorch#11]
after running the code got this error. how can i fix this? plz help.
i used nvidia titan xp gpu.
----------
Traceback (most recent call last):

  File "<ipython-input-4-3c46b487b0a1>", line 1, in <module>
    runfile('C:/Users/User/Desktop/saif/DenseNet-MURA-PyTorch-master/main.py', wdir='C:/Users/User/Desktop/saif/DenseNet-MURA-PyTorch-master')

  File "C:\Users\User\Anaconda3\envs\thesis\lib\site-packages\spyder\utils\site\sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "C:\Users\User\Anaconda3\envs\thesis\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/User/Desktop/saif/DenseNet-MURA-PyTorch-master/main.py", line 51, in <module>
    model = train_model(model, criterion, optimizer, dataloaders, scheduler, dataset_sizes, num_epochs=5)

  File "C:\Users\User\Desktop\saif\DenseNet-MURA-PyTorch-master\train.py", line 30, in train_model
    for i, data in enumerate(dataloaders[phase]):

  File "C:\Users\User\Anaconda3\envs\thesis\lib\site-packages\torch\utils\data\dataloader.py", line 501, in __iter__
    return _DataLoaderIter(self)

  File "C:\Users\User\Anaconda3\envs\thesis\lib\site-packages\torch\utils\data\dataloader.py", line 289, in __init__
    w.start()

  File "C:\Users\User\Anaconda3\envs\thesis\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)

  File "C:\Users\User\Anaconda3\envs\thesis\lib\multiprocessing\context.py", line 212, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)

  File "C:\Users\User\Anaconda3\envs\thesis\lib\multiprocessing\context.py", line 313, in _Popen
    return Popen(process_obj)

  File "C:\Users\User\Anaconda3\envs\thesis\lib\multiprocessing\popen_spawn_win32.py", line 66, in __init__
    reduction.dump(process_obj, to_child)

  File "C:\Users\User\Anaconda3\envs\thesis\lib\multiprocessing\reduction.py", line 59, in dump
    ForkingPickler(file, protocol).dump(obj)

BrokenPipeError: [Errno 32] Broken pipe

**Comment by afmsaif** [comment]
can you give me the loss vs accuracy graphs or loss and accuracy value for all seven type? it would be very helpful for me. i need these value for my under grad thesis purpose , i need to compare them with the result i got from my architecture. 
thanks in advance.

**Comment by pyaf** [comment]
Hi @afmsaif  I'm sorry, I won't be able to help you with this as I'm too busy with my work. I hope you understand.

**Comment by afmsaif** [comment]
can you tell me why BrokenPipeError: [Errno 32] Broken pipe is occurring? that would be helpful too.
thanks in advance.
